### ISSUE TITLE
Broken HackKC image in header

### ISSUE THREAD

**Issue by rockhold** [codeforkansascity/codeforkansascity.github.io#21]
The HackKC image in the carousel of the header is pointing to  http://www.davidlacrone.com/home/hack-kc.png, though it seems it is no longer located at that URL.

![brokenhackkcimage](https://cloud.githubusercontent.com/assets/4065848/15269723/1d7d3920-19ce-11e6-9446-e831120cd213.png)

**Comment by zmon** [comment]
Fixed
